### ISSUE TITLE
US-04 : Cadastrar uma Meta

### ISSUE THREAD

**Issue by TaynaraCris** [FGAUnB-MDS-GM/2021.2-FGAgenda#21]
User Story

Eu, como usuário do produto, desejo cadastrar uma Meta na minha agenda, para saber ao certo o dia que preciso terminar determinada tarefa

Tarefas 

- [x]  Criar Model de Meta
- [x]  Criar Template (HTML/CSS/JS) de Meta
- [x]  Criar Forms de Meta

Critérios de  Aceitação 

- [x] O nome da Meta deve ser único, não sendo permitido o cadastro de Metas com nomes iguais.
- [x] O nome da meta deve ter entre 1 e 20 caracteres, pode conter números e caracteres especiais.
- [x]  A descrição da meta não é obrigatória, mas pode conter entre 1 e 200 caracteres.
- [x]  A meta deve possuir uma data fim associada, não sendo possível cadastrá-lá com dia nem hora que já passaram.
- [x]  A data fim de meta só deve ser possível ser cadastrada com datas a partir do dia seguinte, não sendo possível cadastrar uma meta para o mesmo dia.
- [x] Não é necessário que a meta possua uma TO-DO list associada.
