### ISSUE TITLE
US-07 : Remover uma Meta

### ISSUE THREAD

**Issue by leonardomilv3** [FGAUnB-MDS-GM/2021.2-FGAgenda#35]
User Story

Eu, como usuário do produto, desejo remover uma Meta, caso eu queira, para poder organizar minha agenda

Tarefas 

- [x]  Excluir uma Meta do Banco de Dados

Critérios de  Aceitação 

- [x]  Conseguir excluir uma Meta já cadastrada a partir de um icone deletar.
- [x]  Visualizar no site que a Meta foi excluído

**Comment by TaynaraCris** [comment]
Critérios de aceitação
- [ ] Conseguir selecionar Meta
- [ ] Conseguir deletar uma Meta
- [ ] Não visualizar Meta no Calendário, após ter sido deletada
- [ ] Não visualizar Meta na lista de Metas, após ter sido deletada
